version: "3.3"
services:

  mongo-host:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - "27017:27017"
    volumes:
      - "/tmp/MongoDB:/data/db"
    networks:
      - web-network
  redis-host:
    image: "redis"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - /tmp/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - web-network
  web-host:
    container_name: web-host
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - web-network
    depends_on:
      - mongo-host
  nginx:
    build:
      context: ./nginx
    image: arturcampos/nginx:latest
    container_name: nginx
    networks:
      - web-network
    tty: true
    ports:
      - 80:80
    depends_on:
      - web-host

networks:
  web-network:
    driver: bridge