version: "3.3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - "27017:27017"
    volumes:
      - "/tmp/MongoDB:/data/db"
    networks:
      - mongo-compose-network
  redis:
    image: "redis"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - /tmp/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - node_net

networks:
  mongo-compose-network:
    driver: bridge
  node_net:
    driver: bridge