spring:
  profile: docker

  data:
    mongodb:
      uri: mongodb://root:MongoDB2021!@mongo-host:27017/admin?retryWrites=true&w=majority
      #uri: mongodb://root:MongoDB2021!@localhost:27017/admin?retryWrites=true&w=majority

  cache:
    type: redis
  redis:
    host: redis-host
    #host: localhost
    port: 6379
    password: sOmE_sEcUrE_pAsS

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"


