spring:
  profile: dev

  data:
    mongodb:
      uri: mongodb://root:MongoDB2021!@mongo-host:27017/admin?retryWrites=true&w=majority

  cache:
    type: redis
  redis:
    host: redis-host
    port: 6379
    password: sOmE_sEcUrE_pAsS

server:
  port: 8080
  context:
    path: /api


